product-service:
  build: .
  container_name: product-service-container
  ports:
    - "8082:8082"  # Use a different port than user-service
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce_db
    SPRING_DATASOURCE_USERNAME: postgres
    SPRING_DATASOURCE_PASSWORD: postgres
  depends_on:
    - postgres
